version: '3.7'

services:
  microservice:
    container_name: dummy-microservice
    depends_on:
      - postgresql
    build:
      context: .
      target: DEV
    command: ["npm", "run", "dev"]
    environment:
      NODE_ENV: development
      APP_PORT: 3000
      APP_SECRET: 00000000000000000000000000000000
      DATABASE_URL: postgres://postgres:postgres@postgresql:5432/postgres

    ports:
      - '3000:3000'
    volumes:
      - .:/home/app
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:${APP_PORT}/']
      interval: 1m
      timeout: 10s
      retries: 3

  postgresql:
    container_name: dummy-postgresql
    image: bitnami/postgresql:15
    ports:
      - '5432:5432'
    volumes:
      - postgres_volume:/bitnami/postgresql
    environment:
      POSTGRESQL_USER: postgres
      POSTGRESQL_DATABASE: postgres
      POSTGRESQL_PASSWORD: postgres
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 1m
      timeout: 10s
      retries: 3

volumes:
  postgres_volume:
    driver: local

networks:
  default:
    name: dummy-network
